export default {
    id: '',
    activityName: '',
    originalPrice: '',
    floorPrice: '',
    minReduction: '',
    maxReduction: '',
    targetNum: '',
    restrictTime: '',
    prizeDescription: '',
    activityRule: '',
    prizeInfo: '',
    companyDescription: '',
    commodityDescription: '',
    thumbnail: '',
    discount: '',
    updateUser: '',
    createTime: '',
    updateTime: '',
    qrImg: '',
    gift:'',
    prizeLeft: '',
    latitude: '',
    longitude: '',
    headImage:'',
    footImage:'',
    total_price: '',
    bgImage:'',
    prizeNum:'',
    phone: '',
    address: '',
    showNum: 0,
    maxWin: '',
    intervals:'',
    maxTime:'',
    music: 0,
    extraNum: '',
    prizeRule: '',
    maxTimes: ''
}