export default {
    id: '',
    activityName: '',
    startTime: '',
    endTime: '',
    priceNum: '',
    gift: '',
    targetNum: '',
    restrictTime: '',
    priceDescription: '',
    activityRule: '',
    priceInfo: '',
    companyDescription: '',
    thumbnail: '',
    discount: '',
    updateUser: '',
    createTime: '',
    updateTime: '',
    qrImg: '',
    prizeLeft: '',
    latitude: '',
    longitude: '',
    headImage:'',
    footImage:'',
    bgImage:'',
    phone: '',
    address: ''
}