export default {
    id: '',
    activityName: '',
    startTime: '',
    endTime: '',
    originalPrice: '',
    floorPrice: '',
    minReduction: '',
    maxReduction: '',
    targetNum: '',
    restrictTime: '',
    prizeDescription: '',
    activityRule: '',
    prizeInfo: '',
    companyDescription: '',
    commodityDescription: '',
    thumbnail: '',
    discount: '',
    updateUser: '',
    createTime: '',
    updateTime: '',
    qrImg: '',
    gift:'',
    prizeLeft: '',
    latitude: '',
    longitude: '',
    headImage:'',
    footImage:'',
    total_price: '',
    bgImage:'',
    prizeNum:'',
    phone: '',
    address: ''
}